// Code generated by SQLBoiler 4.3.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dal

var TableNames = struct {
	Chat     string
	Download string
	File     string
	User     string
}{
	Chat:     "chat",
	Download: "download",
	File:     "file",
	User:     "user",
}
