pkgname = "dal"
output = "store/postgres/dal"
no-tests = true
no-hooks = true
no-auto-timestamps = true

wipe = true

[psql]
  dbname = "sfb"
  host   = "localhost"
  port   = 5432
  user   = "sfb"
  pass   = "sfb"
  sslmode = "disable"
  blacklist = [
    "schema_migrations"
  ]

[[types]]
  [types.match]
    type = "types.JSON"
    #nullable = true
  [types.replace]
    type = "string"

