// Code generated by "stringer -type ChatType -trimprefix ChatType"; DO NOT EDIT.

package core

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ChatTypeGroup-1]
	_ = x[ChatTypeSuperGroup-2]
	_ = x[ChatTypeChannel-3]
}

const _ChatType_name = "GroupSuperGroupChannel"

var _ChatType_index = [...]uint8{0, 5, 15, 22}

func (i ChatType) String() string {
	i -= 1
	if i < 0 || i >= ChatType(len(_ChatType_index)-1) {
		return "ChatType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _ChatType_name[_ChatType_index[i]:_ChatType_index[i+1]]
}
